### ISSUE TITLE
Profile Picture

### ISSUE THREAD

**Issue by tesseract-two** [TheKodeToad/TheKodeToad#1]
I noticed your Toad icon got removed (Nintendo ninjas?) so I made a pixel art one (CC0):

![kode_toad_big](https://user-images.githubusercontent.com/118913639/219718297-ca0f346b-a191-4f2c-8b38-c6524d6b661e.png)

Not my finest work, but it looks like Toad. If you want to use it feel free, and if you don't that's okay too! Absolutely no pressure. Here's the original size version: 
![kode_toad](https://user-images.githubusercontent.com/118913639/219718331-25fcad7f-ebea-420a-b915-59409d081263.png)

(Command line because obviously the command line = haxxer)

**Comment by TheKodeToad** [comment]
I mainly removed it because I felt like it, to be honest.
Thanks though!

I have to admit it looks a bit weird without a face though :p.

**Comment by TheKodeToad** [comment]
Hmmm, even thought it's Toad (who is meant to be genderless), it somehow feels a bit dysphoric :joy:. Sorry, but I'm experiencing life things at the moment.

It is a nice icon though! Maybe I'll change my terminal icon to it.

**Comment by TheKodeToad** [comment]
![image](https://user-images.githubusercontent.com/57493648/219866877-d5c8aa25-0757-44fa-8bb5-ef57c3c3ab2b.png)
amazing!

**Comment by tesseract-two** [comment]
> Hmmm, even thought it's Toad (who is meant to be genderless), it somehow feels a bit dysphoric :joy:. Sorry, but I'm experiencing life things at the moment.

Sorry, I hope things get better.
